import React from "react";

import { IPagefindResultData } from "../types";

const importPageFind = async (path: string) =>
  await new Function(`return import("${path}")`)();

export const usePagefind = (
  pagefindPath = "/_next/static/pagefind/pagefind.js",
  baseUrl?: string,
  debounceMs = 150
) => {
  const [search, setSearch] = React.useState<string>("");
  const [isError, setIsError] = React.useState<boolean>(false);
  const [results, setResults] = React.useState<Array<IPagefindResultData>>([]);
  const [loading, setLoading] = React.useState<boolean>(false);

  const catchErrors = React.useCallback(() => {
    setIsError(true);
    window.pagefind = {
      search: () => Promise.resolve({ results: [], query: "" }),
      preload: () => Promise.resolve(),
    };
  }, []);

  const rejectionHandler = (event: PromiseRejectionEvent) => {
    if (event.reason?.message?.includes("Pagefind")) {
      catchErrors();
    }
  };

  React.useEffect(() => {
    async function loadPagefind() {
      if (typeof window.pagefind === "undefined") {
        try {
          const fullPath = pagefindPath;
          const res = await fetch(fullPath, {
            method: "HEAD",
            cache: "no-store",
          });

          if (res.status == 404) throw Error("file not found");

          const pagefind = await importPageFind(fullPath);

          window.pagefind = pagefind;

          // Pagefind derives the site root from its own bundle location, so
          // an index emitted outside `<site>/pagefind` yields result URLs with
          // the bundle path baked in. Correct it before any search runs.
          if (baseUrl) {
            await window.pagefind.options?.({ baseUrl });
          }

          await window.pagefind.preload().catch(catchErrors);
        } catch {
          console.warn(
            `[next-static-search] Pagefind index not found at ${pagefindPath}. ` +
              "It is generated by the pagefind CLI after `next build`; search is disabled until then."
          );
          catchErrors();
        }
      }
    }

    window.addEventListener("unhandledrejection", rejectionHandler);

    loadPagefind();

    return () => {
      window.removeEventListener("unhandledrejection", rejectionHandler);
    };
  }, [pagefindPath, baseUrl]);

  async function handleSearch(s: string) {
    if (!window.pagefind) return;

    const res = await window.pagefind.search(s);
    const result: Array<IPagefindResultData> = [];

    for (const d of res.results) {
      const data = await d?.data();
      if (data) result.push(data);
    }

    setResults(result);
  }

  const debounceRef = React.useRef<ReturnType<typeof setTimeout> | null>(null);
  // Guards against an earlier, slower query overwriting a newer one.
  const queryIdRef = React.useRef(0);

  React.useEffect(
    () => () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    },
    []
  );

  const runSearch = React.useCallback(
    async (s: string, id: number) => {
      if (!s) {
        setResults([]);
        setLoading(false);
        return;
      }
      await handleSearch(s);
      if (queryIdRef.current === id) setLoading(false);
    },
    // handleSearch only reads window.pagefind, which is stable once loaded.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    []
  );

  /**
   * Pagefind fetches index shards per query, so firing on every keystroke is
   * wasteful. Debounce, and drop responses from superseded queries.
   */
  const onSearch = async (s: string) => {
    setSearch(s);
    if (isError) return;

    const id = ++queryIdRef.current;

    if (debounceRef.current) clearTimeout(debounceRef.current);

    if (!s) {
      setResults([]);
      setLoading(false);
      return;
    }

    setLoading(true);

    if (debounceMs <= 0) {
      await runSearch(s, id);
      return;
    }

    debounceRef.current = setTimeout(() => void runSearch(s, id), debounceMs);
  };

  return { isError, results, loading, onSearch, search, setSearch, setLoading };
};

export default usePagefind;
